mySite/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .import views
app_name='accounts'

urlpatterns=[
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup',views.SignUp.as_view(),name='signup'),
    path('edit/',views.EditPage.as_view(),name='edit'),
    path('delete/',views.DeletePage.as_view(),name='delete')
]

mySite/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('blogs/', views.HomeView.as_view(), name='blog-home'),
    path('my-posts/', views.MyPostView.as_view(), name='my-posts'),
    path('saved/', views.SavedPostView.as_view(), name='saved-posts'),
    path('add/', views.AddPostView.as_view(), name='add-post'),
    path('edit/<int:pk>/', views.EditPostView.as_view(), name='edit-post'),
    path('delete/<int:pk>/', views.DeletePostView.as_view(), name='delete-post'),
    path('like/<int:pk>/', views.LikePostView.as_view(), name='like-post'),
    path('save/<int:pk>/', views.SavePostView.as_view(), name='save-post'),
]

mySite/makeNotes/urls.py
from django.urls import path
from .import views
app_name='makeNotes'

urlpatterns=[
    
  path('', views.NoteListView.as_view(), name='note_list'),
    path('new/', views.NoteCreateView.as_view(), name='note_create'),
    path('<int:pk>/edit/', views.NoteUpdateView.as_view(), name='note_edit'),
    path('<int:pk>/delete/', views.NoteDeleteView.as_view(), name='note_delete'),
 path('<int:pk>/download/', views.NoteDownloadView.as_view(), name='note_download'),
    path('upload/', views.NoteUploadView.as_view(), name='note_upload'),
]

mySite/mySite/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    
    path('users/', include('users_app.urls')),

    path('accounts/',include('django.contrib.auth.urls')),

        path('blogs/', include('blog.urls')),
        path('shop/',include('yourShop.urls')),

    path('notes/',include('makeNotes.urls',namespace='makeNotes')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mySite/users_app/urls.py
from django.urls import path
from django.contrib.auth import views 
from .import views
app_name='users_app'

urlpatterns=[
    
    path('', views.UserList.as_view(), name='users'),
    path('users/messages/<str:username>/', views.UserMessages.as_view(), name='user_messages'),

]

mySite/templates/base.html
<!DOCTYPE html>
{% load static %}
<head>

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!--fonts from google fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100..900&display=swap" rel="stylesheet">
 
    <title>Star Social</title>
    <link rel="stylesheet" href="{% static 'css/master.css' %}">
  </head>
  <body>
    <nav>
      <div>
        <a href="{% url 'home' %}">Home</a>
        <ul>
          {% if user.is_authenticated %}
              

            <li><a href="{% url 'users_app:users' %}">users</a></li>
            <li><a href="{% url 'makeNotes:note_list'%}">notes</a></li>
            <li><a href="{% url 'product-list'%}">shop</a></li>
            <li><a href="{% url 'my-products'%}">my product</a></li>
             <li><a href="{% url 'cart'%}">cart</a></li>
            <a href="{% url 'blog-home' %}">All Posts</a> |
        <a href="{% url 'my-posts' %}">My Posts</a> |
        <a href="{% url 'saved-posts' %}">Saved Posts</a> |
        <a href="{% url 'add-post' %}">Add Post</a> |
            <li><a href="#">Create Group</a></li>
            <li>
              <form method="post" action="{% url 'accounts:logout' %}" style="display: inline;">
                {% csrf_token %}
                <button type="submit" style="background:none; border:none; color:blue; cursor:pointer;">
                  Logout
                </button>
              </form>
            </li>
          {% else %}
            <li><a href="#">Groups</a></li>
            <li><a href="{% url 'accounts:login' %}">Login</a></li>
            <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div>
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

mySite/templates/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Welcome to Star Social</h1>
    {% if user.is_authenticated %}
              <h1>Welcome, @{{ user.username }}</h1>
              
              <h1>email{{ user.email }}</h1>
              <li><a href="{% url 'accounts:edit' %}">edit</a></li>
    {% endif %}
{% endblock %}